"""
Session Manager for OK.ru Video Downloader.
Handles authentication and session persistence.
"""

import json
import http.cookiejar
from pathlib import Path
from typing import Optional


class SessionManager:
    """Manages authentication sessions for OK.ru."""
    
    def __init__(self, cookies_dir: Optional[str] = None):
        """
        Initialize SessionManager.
        
        Args:
            cookies_dir: Directory to store cookies. If None, uses default location.
        """
        if cookies_dir is None:
            cookies_dir = Path.home() / ".config" / "ok-video-downloader" / "cookies"
        
        self.cookies_dir = Path(cookies_dir)
        self.cookies_dir.mkdir(parents=True, exist_ok=True)
        self.cookies_file = self.cookies_dir / "ok_cookies.txt"
        self.session_file = self.cookies_dir / "session.json"
        self.is_authenticated = False
        self.username = ""
        
        # Load existing session if available
        self._load_session()
    
    def _load_session(self) -> None:
        """Load existing session from file."""
        if self.session_file.exists():
            try:
                with open(self.session_file, 'r', encoding='utf-8') as f:
                    session_data = json.load(f)
                    self.username = session_data.get('username', '')
                    self.is_authenticated = session_data.get('is_authenticated', False)
                    
                    # Verify cookies file exists
                    if self.is_authenticated and not self.cookies_file.exists():
                        self.is_authenticated = False
            except (json.JSONDecodeError, IOError):
                self.is_authenticated = False
    
    def _save_session(self) -> bool:
        """
        Save current session to file.
        
        Returns:
            True if successful, False otherwise.
        """
        try:
            session_data = {
                'username': self.username,
                'is_authenticated': self.is_authenticated
            }
            
            with open(self.session_file, 'w', encoding='utf-8') as f:
                json.dump(session_data, f, indent=2)
            return True
        except IOError as e:
            print(f"Error saving session: {e}")
            return False
    
    def login(self, username: str, password: str) -> bool:
        """
        Login to OK.ru with credentials.
        
        Args:
            username: OK.ru username or email.
            password: OK.ru password.
        
        Returns:
            True if login successful, False otherwise.
        
        Note:
            This is a placeholder implementation. Actual authentication
            would require browser automation or API integration.
        """
        # This is a simplified implementation
        # In a real scenario, you would:
        # 1. Use selenium or playwright to automate browser login
        # 2. Extract cookies after successful login
        # 3. Save cookies to file in Netscape format for yt-dlp
        
        if not username or not password:
            return False
        
        try:
            # Placeholder: In real implementation, perform actual login
            # For now, we'll create a basic cookies file structure
            self.username = username
            
            # Create cookies file (placeholder)
            # Real implementation would extract actual cookies from browser
            with open(self.cookies_file, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file is generated by OK.ru Video Downloader\n")
                f.write("# Edit at your own risk\n\n")
            
            self.is_authenticated = True
            self._save_session()
            return True
            
        except Exception as e:
            print(f"Login failed: {e}")
            self.is_authenticated = False
            return False

    def logout(self) -> None:
        """Logout and clear session."""
        self.is_authenticated = False
        self.username = ""
        
        # Remove cookies file
        if self.cookies_file.exists():
            try:
                self.cookies_file.unlink()
            except OSError as e:
                print(f"Error removing cookies file: {e}")
        
        # Remove session file
        if self.session_file.exists():
            try:
                self.session_file.unlink()
            except OSError as e:
                print(f"Error removing session file: {e}")
    
    def get_cookies_file(self) -> Optional[str]:
        """
        Get path to cookies file if authenticated.
        
        Returns:
            Path to cookies file if authenticated, None otherwise.
        """
        if self.is_authenticated and self.cookies_file.exists():
            return str(self.cookies_file)
        return None
    
    def is_logged_in(self) -> bool:
        """
        Check if user is logged in.
        
        Returns:
            True if authenticated, False otherwise.
        """
        return self.is_authenticated
    
    def get_username(self) -> str:
        """
        Get current username.
        
        Returns:
            Username if logged in, empty string otherwise.
        """
        return self.username if self.is_authenticated else ""
    
    def import_cookies_from_browser(self, browser: str = "chrome") -> bool:
        """
        Import cookies from browser.
        
        Args:
            browser: Browser name (chrome, firefox, edge, etc.)
        
        Returns:
            True if successful, False otherwise.
        
        Note:
            This is a placeholder. Real implementation would use
            browser_cookie3 or similar library to extract cookies.
        """
        try:
            # Placeholder implementation
            # Real implementation would use browser_cookie3 or similar
            # to extract cookies from the specified browser
            
            # For now, just check if cookies file exists
            if self.cookies_file.exists():
                self.is_authenticated = True
                self._save_session()
                return True
            
            return False
        except Exception as e:
            print(f"Failed to import cookies from {browser}: {e}")
            return False
    
    def import_cookies_from_file(self, file_path: str) -> bool:
        """
        Import cookies from a file.
        
        Args:
            file_path: Path to cookies file (Netscape format).
        
        Returns:
            True if successful, False otherwise.
        """
        try:
            source_file = Path(file_path)
            if not source_file.exists():
                return False
            
            # Copy cookies file
            with open(source_file, 'r', encoding='utf-8') as src:
                content = src.read()
            
            with open(self.cookies_file, 'w', encoding='utf-8') as dst:
                dst.write(content)
            
            self.is_authenticated = True
            self._save_session()
            return True
            
        except Exception as e:
            print(f"Failed to import cookies from file: {e}")
            return False
